{
 "title": "OpenWhisk metrics",
 "description": "Metrics for OpenWhisk",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Invoker Health",
   "type": "timeseries",
   "description": "Display # of healthy and unhealthy invokers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "gauge_loadbalancer_totalHealthyInvokerManaged_counter",
     "legendFormat": "Healthy"
    },
    {
     "expr": "gauge_loadbalancer_totalUnhealthyInvokerManaged_counter",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "description": "JVM memory usage by component as a percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{service!=\"user-events\", region=\"heap\"} / jvm_memory_max_bytes{server!=\"user-events\", region=\"heap\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Activations per Second",
   "type": "timeseries",
   "description": "APS tracked by actions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(openwhisk_action_activations_total[$__rate_interval])",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Activations  per Second",
   "type": "timeseries",
   "description": "APS per invoker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(counter_invoker_activation_start_total[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Action Error Rate",
   "type": "timeseries",
   "description": "Rate of actions failing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(openwhisk_action_status{status!=\"success\"}[$__rate_interval]))\n/\nsum(rate(openwhisk_action_status[$__rate_interval]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Inflight Activations",
   "type": "timeseries",
   "description": "Activations that have not yet been executed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "gauge_loadbalancer_activationsInflight_counter",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "p95 Action Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, action) (rate(openwhisk_action_duration_seconds_bucket[$__rate_interval]))\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Action Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, action) (rate(openwhisk_action_duration_seconds_bucket[$__rate_interval]))\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Action Wait",
   "type": "timeseries",
   "description": "Queuing delay experienced by actions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, action) (rate(openwhisk_action_waitTime_seconds_bucket[$__rate_interval]))\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Action Wait",
   "type": "timeseries",
   "description": "Queuing delay experienced by actions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, action) (rate(openwhisk_action_waitTime_seconds_bucket[$__rate_interval]))\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Action Init",
   "type": "timeseries",
   "description": "Cold start initialization time for actions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, action) (rate(openwhisk_action_initTime_seconds_bucket[$__rate_interval]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Action Init",
   "type": "timeseries",
   "description": "Cold start initialization time for actions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, action) (rate(openwhisk_action_initTime_seconds_bucket[$__rate_interval]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cold Starts",
   "type": "timeseries",
   "description": "Number of cold starts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openwhisk_action_coldStarts_total",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Varied action duration latency",
   "type": "timeseries",
   "description": "Chart to compare action duration at different pXX levels",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, action) (rate(openwhisk_action_duration_seconds_bucket[$__rate_interval]))\n) * 1000",
     "legendFormat": "__auto"
    },
    {
     "aliasTypes": [
      "suffix",
      "prefix",
      "absolute"
     ],
     "query": "A",
     "timeShifts": [
      { "alias": "plain", "id": 0, "value": "1021693s" }
     ],
     "units": [
      "y",
      "M",
      "w",
      "d",
      "h",
      "m",
      "s"
     ]
    }
   ]
  },
  { "title": "Invoker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Containers per Invoker",
   "type": "timeseries",
   "description": "Containers running on each invoker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "gauge_containerPool_activeCount_counter",
     "legendFormat": "{{service}}_active"
    },
    {
     "expr": "gauge_containerPool_idlesCount_counter",
     "legendFormat": "{{service}}_idle"
    },
    {
     "expr": "gauge_containerPool_prewarmCount_counter",
     "legendFormat": "{{service}}_prewarm"
    }
   ]
  },
  {
   "title": "Execution Containers Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of execution containers running on each invoker, grouped by language",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name=~\"wsk.*\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Invoker Container Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of invoker container, mainly used to understand memory cost of WASM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=~\"invoker[0-9]\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Invoker Assignment Overload",
   "type": "timeseries",
   "description": "How often does the load balancer override the intended scheduling process and instead schedules randomly",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "counter_controller_managedInvokerSystemOverload_counter_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invocation Paths",
   "type": "timeseries",
   "description": "Tracks rate of actions going to each invocation path",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(counter_invoker_wasmRun_counter_total[$__rate_interval])",
     "legendFormat": "{{service}}_run"
    },
    {
     "expr": "rate(counter_invoker_wasmServe_counter_total[$__rate_interval])",
     "legendFormat": "{{service}}_serve"
    }
   ]
  }
 ]
}